### ISSUE TITLE
Tags are not being exported

### ISSUE THREAD

**Issue by hrishiballal** [geodesignhub/esri-bridge-v2#15]
When I try to run a export on a "production" version the tags are not being exported, it however works normally locally

**Comment by kbae82** [comment]
I was able to reproduce the issue on Local Dev. Here's a screenshot attached showing the behavior on both Production and Local Dev (Main branch).

Please let me know if you have any questions.
Thank you.

PRD
<img width="1320" alt="FeatureLayer_S7_PRD" src="https://github.com/user-attachments/assets/a91a6245-2a10-4706-bc3c-d8f157b3fe2e" />
Local Dev
<img width="1320" alt="FeatureLayer_S7_Local_Dev" src="https://github.com/user-attachments/assets/54393d5a-a8d0-47f9-9cb7-ada33d38ce8b" />

**Comment by hrishiballal** [comment]
Thanks this is a seperate rendering issue, one of the issues that Brian had was the tag and tag code CSV was not uploaded. I have now updated the code to enable upload in 2.4.0 and test it. 

![upload_test](https://github.com/user-attachments/assets/9b6e357c-d64f-43df-b0c7-57685f83c4d6)
