### ISSUE TITLE
Add a new negotiation details panel

### ISSUE THREAD

**Issue by hrishiballal** [geodesignhub/esri-bridge-v2#6]
Add a new panel in the reporting template called "negotiation details" which is:

Text (Introduction)
Table with two columns (these basically have to images (one in each column)
Table with one column ( image with the output of the negotiation )
Table with two columns (these columns contain images and lists)
Paragraph at the end of the panel

**Comment by kbae82** [comment]
Hello @hrishiballal,

Could you please clarify which section in the sample report aligns with the "Negotiation Details" panel? A screenshot or specific reference would be really helpful to ensure I implement this correctly.

Thank you!

**Comment by hrishiballal** [comment]
Thanks, this is basically the Section 9 and Section 10 of the report I shared with you, it s not exactly the same but I am suggesting a short / condensed version of the bit in Google Docs.
